[[pages]]
path = "pages/about.py"
name = "About"
icon = "ğŸ‘©â€ğŸ’¼"


# SECTION - FORM SUBMISSION
[[pages]]
name = "Form Submission"
icon = "ğŸ¯"
is_section = true

[[pages]]
path = "pages/forms/personal_information.py"
name = "Personal Information"
icon = "ğŸ“"