[[pages]]
path = "pages/about.py"
name = "About"
icon = "ğŸ‘©â€ğŸ’¼"


[[pages]]
path = "pages/custom_form.py"
name = "Generate Custom Form"
icon = "ğŸ§©"

[[pages]]
path = "pages/main.py"
name = "Fill Form"
icon = "âœï¸"

[[pages]]
path = "pages/verify.py"
name = "Verify & Submit"
icon = "âœ…"

[[pages]]
path = "pages/test.py"
name = "DEV"
icon = "ğŸ§©"