[[pages]]
path = "pages/about.py"
name = "About"
icon = "ğŸ‘©â€ğŸ’¼"


[[pages]]
path = 'pages/test.py'
name = 'Dev Test'
icon = 'ğŸ§ª'


[[pages]]
path = "pages/main.py"
name = "Fill in Details"
icon = "ğŸ“"

[[pages]]
path = "pages/verify.py"
name = "Verify & Submit"
icon = "ğŸ“"